### ISSUE TITLE
Video Slider Responsiveness

### ISSUE THREAD

**Issue by ankitaraikundalia** [ThemeFuse/Unyson-Sliders-Extension#11]
Hi,
I am using the video slider in visual builder. However, it is not responsive.
Can you please look into this issue and make it responsive?

**Comment by llemurya** [comment]
@ankitaraikundalia you mean `owl-carousel extension`, if the answer is yes, than read `Owl Carousel` documentation, this is the [link](http://owlcarousel.owlgraphic.com/demos/responsive.html) that explain how to make it responsive, because we only provide the demo , your work is to customize your theme how you want.If it helps please close the issue.Thanks.
